name: ecommerce_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#--------------- PACKAGES ---------------#

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Utility Packages


#----------------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-ExtraLight.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-Light.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-Medium.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-SemiBold.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-Bold.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-Black.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-ExtraLightItalic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-LightItalic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-Italic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-MediumItalic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-SemiBoldItalic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-BoldItalic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/NunitoSans/static/NunitoSans_10pt-BlackItalic.ttf

